language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=lint
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"

install:
 - travis_retry pip install tox-travis

script:
 - tox

after_success:
  - |
    if [[ "$TOXENV" != "lint" ]]; then
      coverage report
      pip install -U codecov
      codecov
    fi
