language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      dist: xenial
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"

install:
 - pip install -U pytest pytest-cov

script:
 - pytest --cov prettytable

after_script:
 - pip install -U flake8
 - flake8 . --statistics --count

after_success:
 - coverage report
 - pip install -U codecov
 - codecov
